### PR TITLE
fix code block style on Chrome

### LINKED ISSUE #338: Ugly code blocks printing since v3.0.0
**Describe the bug**
Since v3.0.0, code blocks are not well rendered (at least on Chrome)

**To Reproduce**
1. Open a note
2. Insert a code block

ex:
>\```sh
>cd $HOME
>echo "alias ll='ls -l'" >> .bashrc
>\```
>

Or with lines beggining with 4 spaces

4. See spaces between lines

**Expected behavior**
There should not be spaces between lines inside a code block

**Screenshots**
https://privatebin.net/?dc65941fb7bc8cb5#D8vbGaBtE1oBYJJLaLEjXM4HYeaNJKbeEGxw9RakSWPk

**Server (please complete the following information):**
- Notes app version: 3.0.0
- Nextcloud version: 16
- OS: Debian 9
- Web server: nginx
- PHP version: 7.3
- Database: mariadb 10.3

**Client (please complete the following information):**
 - Browser (incl. version): Chrome 75
 - OS: Windows

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/76732766-ugly-code-blocks-printing-since-v3-0-0?utm_campaign=plugin&utm_content=tracker%2F46751022&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F46751022&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by korelstar**
fixes  #338

### CODE REVIEW

File: src/components/EditorEasyMDE.vue [hunk 1]
```diff
@@ -159,7 +159,8 @@ export default {
 }
 
 .CodeMirror .cm-comment:only-child {
-	display: block;
+	display: inline-block;
+	width: calc(100% - 1px);
```
Comment (marcelklehr) [inline src/components/EditorEasyMDE.vue]: Ahh, gotta love CSS... :sweat_smile:
